trackingAccounts:
    - name: cloudarchive01
      provider: azure
      location: azure uses name as location
      key1: (/srv/_cert/cloud/azure_key)
      key2: azure only uses key 1

    - name: mongo01
      provider: mongo
      location: (/srv/_cert/cloud/mongo_location)
      key1: (/srv/_cert/cloud/mongo_username)
      key2: (/srv/_cert/cloud/mongo_password)

    - name: elastic01
      provider: elastic
      location: (/srv/_cert/cloud/elastic_location)
      key1: (/srv/_cert/cloud/elastic_username)
      key2: (/srv/_cert/cloud/elastic_password)

storageAccounts:
    - name: cloudarchive01
      provider: azure
      key1: (/srv/_cert/cloud/azure_key)
      key2: azure only uses key 1
        
    - name: cloudarchive02
      provider: s3
      key1: (/srv/_cert/cloud/s3_access_key_id)
      key2: (/srv/_cert/cloud/s3_shared_access_key)
  
areas:
  - name: book_images
    folder: /var/archive/_BOOK
    container: books
    remoteBranch: images
    storage: cloudarchive01
    fileTypes:
        - extension: png
        - extension: svg
        - extension: jpg
        - extension: jpeg
        - extension: gif
          
  - name: book_text
    folder: /var/archive/_BOOK
    container: books
    remoteBranch: text
    storage: cloudarchive01
    tracking: cloudarchive01
    fileTypes:
        - extension: txt
  
  - name: mp3
    folder: /var/archive/_AUDIOTEST
    container: mp3
    storage: cloudarchive01
    tracking: mongo01
    fileTypes:
        - extension: mp3
       
  - name: archives
    remoteBranch: misc
    container: s3 does not use container; use remoteBranch for a remote folder
    folder: /var/archive/_ARCHIVETEST
    storage: cloudarchive02
    fileTypes:
        - extension: zip
        - extension: rar
        - extension: gz
